[app]
title = "MoneyPrinterTurbo"

[llm]
provider = "openai"
api_key = "1zSCqPdSVKbe6okQ"
base_url = "https://text.pollinations.ai/openai"
model_name = "openai"

[pexels]
api_keys = ["H7qUC8PYxjwnyFsIEFfBTqpy5lJ9vViPIX9Q8CW0k53NNhfYb4IHtgCa"]

[pixabay]
api_keys = ["52814173-91f44ee5e49d2a59f9e1742f9"]
