[app]
title = "MoneyPrinterTurbo"

[llm]
provider = "openai"
api_key = "tu-openai-key-aqui"
base_url = "https://api.openai.com/v1"
model_name = "gpt-4"

[pexels]
api_keys = ["tu-pexels-key-aqui"]

[pixabay]
api_keys = ["tu-pixabay-key-aqui"]
